//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescuentosSweet.Model.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULOS()
        {
            this.KITS = new HashSet<KITS>();
        }
    
        public int CODARTICULO { get; set; }
        public string REFERENCIA { get; set; }
        public string REFTECLADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESCRIPADICIONAL { get; set; }
        public byte[] IMAGEN { get; set; }
        public Nullable<int> DPTO { get; set; }
        public Nullable<int> SECCION { get; set; }
        public Nullable<double> UNIDADES { get; set; }
        public Nullable<short> CODTASA1 { get; set; }
        public Nullable<short> CODTASA2 { get; set; }
        public string SUSPENDIDO { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICADO { get; set; }
        public string ESKIT { get; set; }
        public string PORDOSIS { get; set; }
        public string SECOMPRA { get; set; }
        public string SEVENDE { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<double> STOCKMINIMO { get; set; }
        public string UNIDADMEDIDA { get; set; }
        public string NOCOMBINAR { get; set; }
        public string MENU { get; set; }
        public string PORPESO { get; set; }
        public string PRECIOLIBRE { get; set; }
        public Nullable<double> PRECIOMAX { get; set; }
        public Nullable<double> PRECIOMIN { get; set; }
        public Nullable<double> UDSELABORACION { get; set; }
        public Nullable<double> COSTEMEDIO { get; set; }
        public Nullable<double> COSTESTOCK { get; set; }
        public Nullable<double> ULTIMOCOSTE { get; set; }
        public string USASTOCKS { get; set; }
        public Nullable<System.DateTime> FECHAULTCOMPRA { get; set; }
        public Nullable<double> UDSCOMPRADAS { get; set; }
        public Nullable<int> CODTASA1C { get; set; }
        public Nullable<int> CODTASA2C { get; set; }
        public Nullable<int> CODMONEDA { get; set; }
        public Nullable<double> PRECIOULTCOMPRA { get; set; }
        public Nullable<double> ULTDESCCOMERCIAL { get; set; }
        public Nullable<int> COLORFONDO { get; set; }
        public Nullable<int> COLORTEXTO { get; set; }
        public Nullable<double> UNID1C { get; set; }
        public Nullable<double> UNID2C { get; set; }
        public Nullable<double> UNID3C { get; set; }
        public Nullable<double> UNID4C { get; set; }
        public Nullable<double> ULTDTOCOMERCIAL { get; set; }
        public Nullable<double> PRECIOCOMPRAREAL { get; set; }
        public Nullable<double> UDSTRASPASO { get; set; }
        public Nullable<System.DateTime> FACTPORHORA { get; set; }
        public Nullable<int> CONSUMADIC { get; set; }
        public string TIPOARTICULO { get; set; }
        public Nullable<int> NUMCONSUMICIONES { get; set; }
        public string NODISPONIBLE { get; set; }
        public Nullable<double> RENDIMIENTO { get; set; }
        public string DESCATALOGADO { get; set; }
        public string SELECCIONABLEALLTURNOS { get; set; }
        public Nullable<int> MARCA { get; set; }
        public Nullable<short> LINEA { get; set; }
        public Nullable<double> TARA { get; set; }
        public Nullable<int> IDTALONARIO { get; set; }
        public string MEDIDA2 { get; set; }
        public Nullable<bool> NODTOAPLICABLE { get; set; }
        public string AVISOVENTA { get; set; }
        public byte[] VERSION { get; set; }
        public string ESOFERTA { get; set; }
        public string CODCUPON { get; set; }
        public Nullable<int> KCAL { get; set; }
        public Nullable<bool> FACTPORFRANJA { get; set; }
        public Nullable<bool> FORZARUDSENTERASVENTA { get; set; }
        public string ALERGENOS { get; set; }
        public Nullable<bool> VALIDOPRIMERUSO { get; set; }
        public Nullable<bool> COMPLETARPLATOSMENU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KITS> KITS { get; set; }
    }
}
