//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescuentosSweet.Model.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITS
    {
        public int CODARTICULO { get; set; }
        public string TALLA { get; set; }
        public string COLOR { get; set; }
        public int LINEAKIT { get; set; }
        public int CODARTKIT { get; set; }
        public string TALLAKIT { get; set; }
        public string COLORKIT { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCIOKIT { get; set; }
        public string REFERENCIAKIT { get; set; }
        public Nullable<double> UNIDADES { get; set; }
        public Nullable<double> PRECIOUNIDAD { get; set; }
        public Nullable<double> TOTALLINEA { get; set; }
        public string IMPRIMIRLINEA { get; set; }
        public byte[] VERSION { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
    }
}
