//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescuentosSweet.Model.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASPALMACEN
    {
        public string SERIE { get; set; }
        public int NUMERO { get; set; }
        public int LINEA { get; set; }
        public string CODALMORIG { get; set; }
        public string CODALMDEST { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CODARTICULO { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> UNIDADES { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public Nullable<int> CAJA { get; set; }
        public Nullable<int> Z { get; set; }
        public Nullable<double> STOCK { get; set; }
        public string DESCARGADO { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<int> IMPRESIONES { get; set; }
        public Nullable<bool> ESRECUENTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDMOTIVO { get; set; }
        public string DESCMOTIVO { get; set; }
    }
}
