//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescuentosSweet.Model.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDORES
    {
        public int CODVENDEDOR { get; set; }
        public string PASSWORDENTRADA { get; set; }
        public string NOMBREVENDEDOR { get; set; }
        public string NOMBRECORTO { get; set; }
        public Nullable<double> COMISION { get; set; }
        public byte[] IMAGEN { get; set; }
        public string MODULOZ { get; set; }
        public string MODULOX { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> TIPOEMPLEADO { get; set; }
        public string PASSWORDREGISTRO { get; set; }
        public Nullable<int> CODIGORF { get; set; }
        public string DESCATALOGADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<double> COSTEHORA { get; set; }
        public Nullable<double> COSTEHORAEXTRA { get; set; }
        public string DIRECCION { get; set; }
        public string CODPOSTAL { get; set; }
        public string POBLACION { get; set; }
        public string DNI { get; set; }
        public string TELEFONO { get; set; }
        public string MOBIL { get; set; }
        public Nullable<System.DateTime> FECHAENTRADA { get; set; }
        public Nullable<int> IDHOTEL { get; set; }
        public string NEWPASSWORDENTRADA { get; set; }
        public string NEWPASSWORDREGISTRO { get; set; }
        public Nullable<int> NUMARTICULOSBORRADOS { get; set; }
        public byte[] VERSION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<double> COSTEHORAEXTRA2 { get; set; }
        public string PASSWORDENTRADARFID { get; set; }
        public string PASSWORDREGISTRORFID { get; set; }
    }
}
