//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sweetcoffee.Model.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALMACEN
    {
        public string CODALMACEN { get; set; }
        public string NOMBREALMACEN { get; set; }
        public string POBLACION { get; set; }
        public string PROVINCIA { get; set; }
        public string NOTAS { get; set; }
        public string N { get; set; }
        public string CENTROCOSTE { get; set; }
        public Nullable<double> STOCKMINIMO { get; set; }
        public Nullable<double> STOCKMAXIMO { get; set; }
        public Nullable<double> FACTOR { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string SERIETRASPASOS { get; set; }
        public Nullable<int> CODEMPRESACONTABLE { get; set; }
        public Nullable<int> VALORACIONTRASPASOS { get; set; }
        public Nullable<int> PVPETIQUETAS { get; set; }
        public Nullable<int> VALORACIONINVENTARIO { get; set; }
    }
}
